---
- name: Add Docker repository GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Add Docker CE repo
  apt_repository:
    repo: deb [arch={{ architecture[ansible_architecture] }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_repository }}
    filename: docker-ce

- name: Install Docker related packages
  apt:
    name: "{{ item }}"
  with_items:
    - docker-ce
    - python
    - python-pip
    - python-setuptools
    - libffi-dev
    - python-backports.ssl-match-hostname

- name: Install docker and docker-compose
  pip:
    state: latest
    name:
      - docker
      - docker-compose

- name: Add users to the docker group
  user:
    name: "{{ item }}"
    groups:
      - docker
  with_items: "{{ docker_users }}"
